import type { Metadata } from "next";
// @ts-ignore

import "./globals.css";
// @ts-ignore

import "./editor/Editor.css";

import { ThemeProvider } from "@/components/theme-provider";
import { robotoFlex, roboto, robotoMono } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "MyPath",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${robotoFlex.variable} ${roboto.variable} ${robotoMono.variable} font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}